#!/usr/bin/pythono3

def raise_exception(message=""):
    raise NameError(message)
